### ISSUE TITLE
Better Pest doesn't run tests anymore

### ISSUE THREAD

**Issue by KenGuggelmeyer** [m1guelpf/better-phpunit#14]
## What are the steps to reproduce this issue?

1. Open up test file
2. Run a better pest command. Via shortcut or via command palette
3. …

## What happens?
Nothing. The integrated terminal gets cleared but there is no feedback

## What were you expecting to happen?
Feedback of the tests that should be running

## Any logs, error output, etc?
No errors, no logs found

## Any other comments?
My terminal is configured to zsh. Running pest manually via the terminal does run.

## What versions are you using?
**Operating System:** Mac OS Ventura
**Package Version:** v0.1.0

**Comment by felixele217** [comment]
Having the same issue. Loving the package since it is absolutely a gamechanger, so highly looking forward to a fix. :)

**Comment by felixele217** [comment]
Ok, one tip: Check your VSCode Keyboard Shortcuts and see if you assigned the Better PHPUnit Shortcut to the same shortcut. Removing it fixed for me.

**Comment by KenGuggelmeyer** [comment]
I have no duplicate keybindings assigned:
![image](https://user-images.githubusercontent.com/22051138/223437346-ea5a18ab-ab68-4353-ab7e-76c479b485ca.png)
![image](https://user-images.githubusercontent.com/22051138/223437453-ee908ece-6a57-4d95-b8fe-f51b443125db.png)

**Comment by felixele217** [comment]
ok nevermind it stopped working for me after a time as well. so we have to wait for the maintainers

**Comment by felixele217** [comment]
@KenGuggelmeyer okay another thing that might cause the problem: uninstalling the better phpunit extension made better pest working for me again. but the run command only works after I initially executed the run previous command. 

So if you have that installed try uninstalling it and then try any better pest command and see if it works.

**Comment by KenGuggelmeyer** [comment]
> @KenGuggelmeyer okay another thing that might cause the problem: uninstalling the better phpunit extension made better pest working for me again. but the run command only works after I initially executed the run previous command.
> 
> So if you have that installed try uninstalling it and then try any better pest command and see if it works.

This worked. I've uninstalled everything related to phpunit except  better pest and it started working again!

**Comment by felixele217** [comment]
anyways it would somehow nice if the authors could mention it somewhere that this could lead to problems so that others wont run into the same issue 🙏
