### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by tm1000** [m1guelpf/better-phpunit#16]
This is the officially recommended version to use from https://pestphp.com/docs/editor-setup. Yet it hasnt had updates since October 25, 2020. 

- There are pull requests here that are over a year old
- There are issues that have never been resolved
- In VSCode there is the ability to now list tests visually which would be a nice addition to this extension (See: https://marketplace.visualstudio.com/items?itemName=chiefmyron.phpunit-test-workbench)

By the way, I'm the maintainer for the Psalm VSCode plugin (https://github.com/psalm/psalm-vscode-plugin)

@m1guelpf would you be willing to add collaborators? I'd be willing to work on these.

**Comment by m1guelpf** [comment]
Sure, would love to get some help maintaining the project! :D

**Comment by tm1000** [comment]
@m1guelpf Add me to the project or if you want discuss you can email me at: andrew.nagy@the159.com

Looking forward to helping out!
