### ISSUE TITLE
Delay before running tests

### ISSUE THREAD

**Issue by GoodM4ven** [m1guelpf/better-phpunit#20]
## What are the steps to reproduce this issue?

1. Have Better Pest extension installed
2. Spin up a new laravel project with Breeze into Pest
3. Open up the example test file
4. Run the test using Better Pest's keybinding

## What happens?
Terminal is delayed for around 5 seconds, then it opens up and the testing **begins**.

## What were you expecting to happen?
Expected the terminal to open up instantly and begin testing.

## Any logs, error output, etc?
Observation 1: If the same terminal stays up, then I run the test again (like using the "run the previous test" command), then the terminal clears up except for the first circle (being emptied), then everything is delayed for about 5 seconds, then the testing begins by then!
Observation 2: There is no delay with pest tests ran through `php artisan test` at any point in time.

## Any other comments?
Workaround: If I run Better PHPUnit to test the pest file, I get the error, but then the response from VSC is back to normal; instantly running the tests using Better Pest's keybinding! That error has to be triggered in order to do something to VSC and make it respond normally to testing!

## What versions are you using?
**Operating System:** 5.19.0-43-generic #44-Ubuntu x86_64 GNU/Linux
**Package Version:** 0.1.0
**VSC Version:** 1.79.0

**Comment by ariStridely** [comment]
Any updates? It really slow down TDD process...

**Comment by GoodM4ven** [comment]
@ariStridely Listen, [Better PHPUnit](https://marketplace.visualstudio.com/items?itemName=calebporzio.better-phpunit) extension was updated by [Caleb Porzio](https://twitter.com/calebporzio) to fallback to using Pest without the delay. Basically, use that extension alone and you're good to go.

If only they do offer the extension on [open-VSX](https://open-vsx.org/) or something... (sigh)
