### ISSUE TITLE
Upload the extension on Open VSX

### ISSUE THREAD

**Issue by GoodM4ven** [m1guelpf/better-phpunit#23]
Hey there,

Would you kindly make the extension available on [VSX](https://open-vsx.org/), so we can download it in [VSCodium](https://vscodium.com/)?

Thanks.

**Comment by bilogic** [comment]
Is it on https://open-vsx.org/?

<blockquote></blockquote>

**Comment by GoodM4ven** [comment]
@bilogic No.

I'm using now [better-phpunit](https://marketplace.visualstudio.com/items?itemName=calebporzio.better-phpunit) and installing it manually. And even though it's also not available on VSX, it handles both cases gracefully (Pest and PHPUnit at once).

**Comment by bilogic** [comment]
Does it handle pest? Do you mind sharing your config?

**Comment by GoodM4ven** [comment]
I do not have any configuration for it. I use a VSC workspace on top of local services all installed in "TALL" projects using [lara-stacker](https://github.com/GoodM4ven/lara-stacker). You could however check [these](https://github.com/VPremiss/TALL-STANDARDS) settings and extensions too.
